In [ ]:
import pandas as pd

In [ ]:
import numpy as np

In [ ]:
import matplotlib.pyplot as plt

In [ ]:
data = """About the Program
What is the course fee for  Data Science Mentorship Program (DSMP 2023)
The course follows a monthly subscription model where you have to make monthly payments of Rs 799/month.
What is the total duration of the course?
The total duration of the course is 7 months. So the total course fee becomes 799*7 = Rs 5600(approx.)
What is the syllabus of the mentorship program?
We will be covering the following modules:
Python Fundamentals
Python libraries for Data Science
Data Analysis
SQL for Data Science
Maths for Machine Learning
ML Algorithms
Practical ML
MLOPs
Case studies
You can check the detailed syllabus here - https://learnwith.campusx.in/courses/CampusX-Data-Science-Mentorship-Program-637339afe4b0615a1bbed390
Will Deep Learning and NLP be a part of this program?
No, NLP and Deep Learning both are not a part of this program’s curriculum.
What if I miss a live session? Will I get a recording of the session?
Yes all our sessions are recorded, so even if you miss a session you can go back and watch the recording.
Where can I find the class schedule?
Checkout this google sheet to see month by month time table of the course - https://docs.google.com/spreadsheets/d/16OoTax_A6ORAeCg4emgexhqqPv3noQPYKU7RJ6ArOzk/edit?usp=sharing.
What is the time duration of all the live sessions?
Roughly, all the sessions last 2 hours.
What is the language spoken by the instructor during the sessions?
Hinglish
How will I be informed about the upcoming class?
You will get a mail from our side before every paid session once you become a paid user.
Can I do this course if I am from a non-tech background?
Yes, absolutely.
I am late, can I join the program in the middle?
Absolutely, you can join the program anytime.
If I join/pay in the middle, will I be able to see all the past lectures?
Yes, once you make the payment you will be able to see all the past content in your dashboard.
Where do I have to submit the task?
You don’t have to submit the task. We will provide you with the solutions, you have to self evaluate the task yourself.
Will we do case studies in the program?
Yes.
Where can we contact you?
You can mail us at nitish.campusx@gmail.com
Payment/Registration related questions
Where do we have to make our payments? Your YouTube channel or website?
You have to make all your monthly payments on our website. Here is the link for our website - https://learnwith.campusx.in/
Can we pay the entire amount of Rs 5600 all at once?
Unfortunately no, the program follows a monthly subscription model.
What is the validity of monthly subscription? Suppose if I pay on 15th Jan, then do I have to pay again on 1st Feb or 15th Feb
15th Feb. The validity period is 30 days from the day you make the payment. So essentially you can join anytime you don’t have to wait for a month to end.
What if I don’t like the course after making the payment. What is the refund policy?
You get a 7 days refund period from the day you have made the payment.
I am living outside India and I am not able to make the payment on the website, what should I do?
You have to contact us by sending a mail at nitish.campusx@gmail.com
Post registration queries
Till when can I view the paid videos on the website?
This one is tricky, so read carefully. You can watch the videos till your subscription is valid. Suppose you have purchased subscription on 21st Jan, you will be able to watch all the past paid sessions in the period of 21st Jan to 20th Feb. But after 21st Feb you will have to purchase the subscription again.
But once the course is over and you have paid us Rs 5600(or 7 installments of Rs 799) you will be able to watch the paid sessions till Aug 2024.
Why lifetime validity is not provided?
Because of the low course fee.
Where can I reach out in case of a doubt after the session?
You will have to fill a google form provided in your dashboard and our team will contact you for a 1 on 1 doubt clearance session
If I join the program late, can I still ask past week doubts?
Yes, just select past week doubt in the doubt clearance google form.
I am living outside India and I am not able to make the payment on the website, what should I do?
You have to contact us by sending a mail at nitish.campusx@gmai.com
Certificate and Placement Assistance related queries
What is the criteria to get the certificate?
There are 2 criterias:
You have to pay the entire fee of Rs 5600
You have to attempt all the course assessments.
I am joining late. How can I pay payment of the earlier months?
You will get a link to pay fee of earlier months in your dashboard once you pay for the current month.
I have read that Placement assistance is a part of this program. What comes under Placement assistance?
This is to clarify that Placement assistance does not mean Placement guarantee. So we dont guarantee you any jobs or for that matter even interview calls. So if you are planning to join this course just for placements, I am afraid you will be disappointed. Here is what comes under placement assistance
Portfolio Building sessions
Soft skill sessions
Sessions with industry mentors
Discussion on Job hunting strategies
"""

In [ ]:
data

'About the Program\nWhat is the course fee for  Data Science Mentorship Program (DSMP 2023)\nThe course follows a monthly subscription model where you have to make monthly payments of Rs 799/month.\nWhat is the total duration of the course?\nThe total duration of the course is 7 months. So the total course fee becomes 799*7 = Rs 5600(approx.)\nWhat is the syllabus of the mentorship program?\nWe will be covering the following modules:\nPython Fundamentals\nPython libraries for Data Science\nData Analysis\nSQL for Data Science\nMaths for Machine Learning\nML Algorithms\nPractical ML\nMLOPs\nCase studies\nYou can check the detailed syllabus here - https://learnwith.campusx.in/courses/CampusX-Data-Science-Mentorship-Program-637339afe4b0615a1bbed390\nWill Deep Learning and NLP be a part of this program?\nNo, NLP and Deep Learning both are not a part of this program’s curriculum.\nWhat if I miss a live session? Will I get a recording of the session?\nYes all our sessions are recorded, so eve

In [ ]:
import tensorflow as tf

In [ ]:
from tensorflow.keras.preprocessing.text import Tokenizer

In [ ]:
tokenizer = Tokenizer()

In [ ]:
tokenizer

In [ ]:
tokenizer.fit_on_texts([data])

In [ ]:
tokenizer.word_index

{'the': 1,
 'you': 2,
 'i': 3,
 'to': 4,
 'a': 5,
 'of': 6,
 'is': 7,
 'have': 8,
 'will': 9,
 'can': 10,
 'what': 11,
 'course': 12,
 'program': 13,
 'in': 14,
 'for': 15,
 'all': 16,
 'sessions': 17,
 'on': 18,
 'be': 19,
 'and': 20,
 'this': 21,
 'if': 22,
 'am': 23,
 'pay': 24,
 'payment': 25,
 'make': 26,
 'we': 27,
 'do': 28,
 'subscription': 29,
 'where': 30,
 'rs': 31,
 'so': 32,
 'campusx': 33,
 'session': 34,
 'our': 35,
 'paid': 36,
 'join': 37,
 'able': 38,
 'your': 39,
 'website': 40,
 'placement': 41,
 'fee': 42,
 'data': 43,
 'monthly': 44,
 'month': 45,
 'not': 46,
 'get': 47,
 'yes': 48,
 'once': 49,
 'past': 50,
 'feb': 51,
 'assistance': 52,
 'science': 53,
 '7': 54,
 '5600': 55,
 'are': 56,
 'watch': 57,
 'google': 58,
 'by': 59,
 'com': 60,
 'mail': 61,
 'from': 62,
 'contact': 63,
 'us': 64,
 'at': 65,
 'or': 66,
 'doubt': 67,
 'mentorship': 68,
 'payments': 69,
 '799': 70,
 'total': 71,
 'duration': 72,
 'months': 73,
 'learning': 74,
 'case': 75,
 'here': 76,
 '

In [ ]:
dic_word = tokenizer.word_index

In [ ]:
dic_word

{'the': 1,
 'you': 2,
 'i': 3,
 'to': 4,
 'a': 5,
 'of': 6,
 'is': 7,
 'have': 8,
 'will': 9,
 'can': 10,
 'what': 11,
 'course': 12,
 'program': 13,
 'in': 14,
 'for': 15,
 'all': 16,
 'sessions': 17,
 'on': 18,
 'be': 19,
 'and': 20,
 'this': 21,
 'if': 22,
 'am': 23,
 'pay': 24,
 'payment': 25,
 'make': 26,
 'we': 27,
 'do': 28,
 'subscription': 29,
 'where': 30,
 'rs': 31,
 'so': 32,
 'campusx': 33,
 'session': 34,
 'our': 35,
 'paid': 36,
 'join': 37,
 'able': 38,
 'your': 39,
 'website': 40,
 'placement': 41,
 'fee': 42,
 'data': 43,
 'monthly': 44,
 'month': 45,
 'not': 46,
 'get': 47,
 'yes': 48,
 'once': 49,
 'past': 50,
 'feb': 51,
 'assistance': 52,
 'science': 53,
 '7': 54,
 '5600': 55,
 'are': 56,
 'watch': 57,
 'google': 58,
 'by': 59,
 'com': 60,
 'mail': 61,
 'from': 62,
 'contact': 63,
 'us': 64,
 'at': 65,
 'or': 66,
 'doubt': 67,
 'mentorship': 68,
 'payments': 69,
 '799': 70,
 'total': 71,
 'duration': 72,
 'months': 73,
 'learning': 74,
 'case': 75,
 'here': 76,
 '

In [ ]:
len(tokenizer.word_index)

282

In [ ]:

data

'About the Program\nWhat is the course fee for  Data Science Mentorship Program (DSMP 2023)\nThe course follows a monthly subscription model where you have to make monthly payments of Rs 799/month.\nWhat is the total duration of the course?\nThe total duration of the course is 7 months. So the total course fee becomes 799*7 = Rs 5600(approx.)\nWhat is the syllabus of the mentorship program?\nWe will be covering the following modules:\nPython Fundamentals\nPython libraries for Data Science\nData Analysis\nSQL for Data Science\nMaths for Machine Learning\nML Algorithms\nPractical ML\nMLOPs\nCase studies\nYou can check the detailed syllabus here - https://learnwith.campusx.in/courses/CampusX-Data-Science-Mentorship-Program-637339afe4b0615a1bbed390\nWill Deep Learning and NLP be a part of this program?\nNo, NLP and Deep Learning both are not a part of this program’s curriculum.\nWhat if I miss a live session? Will I get a recording of the session?\nYes all our sessions are recorded, so eve

In [ ]:
data.split("\n")

['About the Program',
 'What is the course fee for  Data Science Mentorship Program (DSMP 2023)',
 'The course follows a monthly subscription model where you have to make monthly payments of Rs 799/month.',
 'What is the total duration of the course?',
 'The total duration of the course is 7 months. So the total course fee becomes 799*7 = Rs 5600(approx.)',
 'What is the syllabus of the mentorship program?',
 'We will be covering the following modules:',
 'Python Fundamentals',
 'Python libraries for Data Science',
 'Data Analysis',
 'SQL for Data Science',
 'Maths for Machine Learning',
 'ML Algorithms',
 'Practical ML',
 'MLOPs',
 'Case studies',
 'You can check the detailed syllabus here - https://learnwith.campusx.in/courses/CampusX-Data-Science-Mentorship-Program-637339afe4b0615a1bbed390',
 'Will Deep Learning and NLP be a part of this program?',
 'No, NLP and Deep Learning both are not a part of this program’s curriculum.',
 'What if I miss a live session? Will I get a recording 

In [ ]:
import time

In [ ]:
for sentence in data.split("\n"):
    tokenized_sentence = tokenizer.texts_to_sequences([sentence])
    print(tokenized_sentence)
    print(tokenized_sentence[0])
    print()
    time.sleep(3)


[[93, 1, 13]]
[93, 1, 13]

[[11, 7, 1, 12, 42, 15, 43, 53, 68, 13, 147, 148]]
[11, 7, 1, 12, 42, 15, 43, 53, 68, 13, 147, 148]



KeyboardInterrupt: 

In [ ]:
dic_word["about"]

93

In [ ]:
dic_word["to"]

4

In [ ]:
dic_word["program"]

13

In [ ]:
input_sequence = []
for sentence in data.split("\n"):
    tokenized_sentence = tokenizer.texts_to_sequences([sentence])[0]

    for i in range(1, len(tokenized_sentence)):
        input_sequence.append(tokenized_sentence[ : i + 1])

In [ ]:
input_sequence

[[93, 1],
 [93, 1, 13],
 [11, 7],
 [11, 7, 1],
 [11, 7, 1, 12],
 [11, 7, 1, 12, 42],
 [11, 7, 1, 12, 42, 15],
 [11, 7, 1, 12, 42, 15, 43],
 [11, 7, 1, 12, 42, 15, 43, 53],
 [11, 7, 1, 12, 42, 15, 43, 53, 68],
 [11, 7, 1, 12, 42, 15, 43, 53, 68, 13],
 [11, 7, 1, 12, 42, 15, 43, 53, 68, 13, 147],
 [11, 7, 1, 12, 42, 15, 43, 53, 68, 13, 147, 148],
 [1, 12],
 [1, 12, 94],
 [1, 12, 94, 5],
 [1, 12, 94, 5, 44],
 [1, 12, 94, 5, 44, 29],
 [1, 12, 94, 5, 44, 29, 95],
 [1, 12, 94, 5, 44, 29, 95, 30],
 [1, 12, 94, 5, 44, 29, 95, 30, 2],
 [1, 12, 94, 5, 44, 29, 95, 30, 2, 8],
 [1, 12, 94, 5, 44, 29, 95, 30, 2, 8, 4],
 [1, 12, 94, 5, 44, 29, 95, 30, 2, 8, 4, 26],
 [1, 12, 94, 5, 44, 29, 95, 30, 2, 8, 4, 26, 44],
 [1, 12, 94, 5, 44, 29, 95, 30, 2, 8, 4, 26, 44, 69],
 [1, 12, 94, 5, 44, 29, 95, 30, 2, 8, 4, 26, 44, 69, 6],
 [1, 12, 94, 5, 44, 29, 95, 30, 2, 8, 4, 26, 44, 69, 6, 31],
 [1, 12, 94, 5, 44, 29, 95, 30, 2, 8, 4, 26, 44, 69, 6, 31, 70],
 [1, 12, 94, 5, 44, 29, 95, 30, 2, 8, 4, 26, 44, 69, 6

In [ ]:
for x in input_sequence:
  print(x)
  print(len(x))
  time.sleep(2)

[93, 1]
2
[93, 1, 13]
3
[11, 7]
2
[11, 7, 1]
3
[11, 7, 1, 12]
4
[11, 7, 1, 12, 42]
5
[11, 7, 1, 12, 42, 15]
6


KeyboardInterrupt: 

In [ ]:
max( [ len(x)    for x in input_sequence] )

57

In [ ]:
max_len = max( [ len(x)    for x in input_sequence] )

In [ ]:
max_len

57

In [ ]:
from tensorflow.keras.preprocessing.sequence import pad_sequences

In [ ]:
input_sequence

[[93, 1],
 [93, 1, 13],
 [11, 7],
 [11, 7, 1],
 [11, 7, 1, 12],
 [11, 7, 1, 12, 42],
 [11, 7, 1, 12, 42, 15],
 [11, 7, 1, 12, 42, 15, 43],
 [11, 7, 1, 12, 42, 15, 43, 53],
 [11, 7, 1, 12, 42, 15, 43, 53, 68],
 [11, 7, 1, 12, 42, 15, 43, 53, 68, 13],
 [11, 7, 1, 12, 42, 15, 43, 53, 68, 13, 147],
 [11, 7, 1, 12, 42, 15, 43, 53, 68, 13, 147, 148],
 [1, 12],
 [1, 12, 94],
 [1, 12, 94, 5],
 [1, 12, 94, 5, 44],
 [1, 12, 94, 5, 44, 29],
 [1, 12, 94, 5, 44, 29, 95],
 [1, 12, 94, 5, 44, 29, 95, 30],
 [1, 12, 94, 5, 44, 29, 95, 30, 2],
 [1, 12, 94, 5, 44, 29, 95, 30, 2, 8],
 [1, 12, 94, 5, 44, 29, 95, 30, 2, 8, 4],
 [1, 12, 94, 5, 44, 29, 95, 30, 2, 8, 4, 26],
 [1, 12, 94, 5, 44, 29, 95, 30, 2, 8, 4, 26, 44],
 [1, 12, 94, 5, 44, 29, 95, 30, 2, 8, 4, 26, 44, 69],
 [1, 12, 94, 5, 44, 29, 95, 30, 2, 8, 4, 26, 44, 69, 6],
 [1, 12, 94, 5, 44, 29, 95, 30, 2, 8, 4, 26, 44, 69, 6, 31],
 [1, 12, 94, 5, 44, 29, 95, 30, 2, 8, 4, 26, 44, 69, 6, 31, 70],
 [1, 12, 94, 5, 44, 29, 95, 30, 2, 8, 4, 26, 44, 69, 6

In [ ]:
padded_input_sequence = pad_sequences(input_sequence, maxlen= max_len, padding = "pre")

In [ ]:
input_sequence[0]

[93, 1]

In [ ]:
padded_input_sequence[0]

array([ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0, 93,  1], dtype=int32)

In [ ]:
len(padded_input_sequence[0])

57

In [ ]:
input_sequence[8]

[11, 7, 1, 12, 42, 15, 43, 53]

In [ ]:
padded_input_sequence[8]

array([ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 11,  7,
        1, 12, 42, 15, 43, 53], dtype=int32)

In [ ]:
padded_input_sequence

array([[  0,   0,   0, ...,   0,  93,   1],
       [  0,   0,   0, ...,  93,   1,  13],
       [  0,   0,   0, ...,   0,  11,   7],
       ...,
       [  0,   0,   0, ..., 279,  18, 280],
       [  0,   0,   0, ...,  18, 280, 281],
       [  0,   0,   0, ..., 280, 281, 282]], dtype=int32)

In [ ]:
padded_input_sequence.shape

(863, 57)

In [ ]:
padded_input_sequence[0]

array([ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0, 93,  1], dtype=int32)

In [ ]:
padded_input_sequence[3]

array([ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0, 11,  7,  1], dtype=int32)

In [ ]:
padded_input_sequence[ :  , : -1]

array([[  0,   0,   0, ...,   0,   0,  93],
       [  0,   0,   0, ...,   0,  93,   1],
       [  0,   0,   0, ...,   0,   0,  11],
       ...,
       [  0,   0,   0, ...,   0, 279,  18],
       [  0,   0,   0, ..., 279,  18, 280],
       [  0,   0,   0, ...,  18, 280, 281]], dtype=int32)

In [ ]:
X = padded_input_sequence[ : , : -1 ]

In [ ]:
X

array([[  0,   0,   0, ...,   0,   0,  93],
       [  0,   0,   0, ...,   0,  93,   1],
       [  0,   0,   0, ...,   0,   0,  11],
       ...,
       [  0,   0,   0, ...,   0, 279,  18],
       [  0,   0,   0, ..., 279,  18, 280],
       [  0,   0,   0, ...,  18, 280, 281]], dtype=int32)

In [ ]:
y = padded_input_sequence[ : , -1 ]

In [ ]:
y

array([  1,  13,   7,   1,  12,  42,  15,  43,  53,  68,  13, 147, 148,
        12,  94,   5,  44,  29,  95,  30,   2,   8,   4,  26,  44,  69,
         6,  31,  70,  45,   7,   1,  71,  72,   6,   1,  12,  71,  72,
         6,   1,  12,   7,  54,  73,  32,   1,  71,  12,  42, 149,  70,
        54,  31,  55, 150,   7,   1,  96,   6,   1,  68,  13,   9,  19,
       151,   1, 152, 153, 154, 155,  15,  43,  53, 156,  15,  43,  53,
        15, 159,  74, 160,  98,  99,  10, 163,   1, 164,  96,  76,  77,
       100,  33,  14, 165,  33,  43,  53,  68,  13, 166, 101,  74,  20,
       102,  19,   5,  78,   6,  21,  13, 102,  20, 101,  74, 167,  56,
        46,   5,  78,   6,  21, 168, 169,  22,   3, 104,   5, 105,  34,
         9,   3,  47,   5, 106,   6,   1,  34,  16,  35,  17,  56, 170,
        32, 107,  22,   2, 104,   5,  34,   2,  10, 171, 172,  20,  57,
         1, 106,  10,   3, 173,   1, 108, 174,  21,  58, 176,   4,  79,
        45,  59,  45, 109, 177,   6,   1,  12,  77, 178,  58,  6

In [ ]:
X.shape

(863, 56)

In [ ]:
y.shape

(863,)

In [ ]:
from tensorflow.keras.utils import to_categorical

In [ ]:
max(y)

282

In [ ]:
max(y)+1

283

In [ ]:
y.shape

(863,)

In [ ]:
y = to_categorical(y,num_classes=283)

In [ ]:
y.shape

(863, 283)

# **Sequential Model Building**

In [ ]:
from tensorflow.keras.models import Sequential

In [ ]:
from tensorflow.keras.layers import Embedding, Dense, LSTM

In [ ]:
import warnings

In [ ]:
warnings.filterwarnings("ignore")

In [ ]:
model = Sequential()

In [ ]:
model.add(Embedding(283, 100, input_length = 56))

In [ ]:
model.add(LSTM(150))

In [ ]:
model.add(Dense(283, activation = "softmax"))

In [ ]:
model.compile(optimizer= "adam",
              loss = "categorical_crossentropy",
              metrics = ["accuracy"])

In [ ]:
model.summary()

Model: "sequential_1"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓
┃ Layer (type)                         ┃ Output Shape                ┃         Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━┩
│ embedding_1 (Embedding)              │ ?                           │     0 (unbuilt) │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ lstm_1 (LSTM)                        │ ?                           │     0 (unbuilt) │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_1 (Dense)                      │ ?                           │     0 (unbuilt) │
└──────────────────────────────────────┴─────────────────────────────┴─────────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

In [ ]:
model.fit(X, y, epochs = 50)

Epoch 1/50
27/27 ━━━━━━━━━━━━━━━━━━━━ 4s 161ms/step - accuracy: 0.9538 - loss: 0.3344
Epoch 2/50
27/27 ━━━━━━━━━━━━━━━━━━━━ 3s 101ms/step - accuracy: 0.9481 - loss: 0.3238
Epoch 3/50
27/27 ━━━━━━━━━━━━━━━━━━━━ 3s 101ms/step - accuracy: 0.9420 - loss: 0.3229
Epoch 4/50
27/27 ━━━━━━━━━━━━━━━━━━━━ 3s 101ms/step - accuracy: 0.9506 - loss: 0.3022
Epoch 5/50
27/27 ━━━━━━━━━━━━━━━━━━━━ 4s 161ms/step - accuracy: 0.9576 - loss: 0.2658
Epoch 6/50
27/27 ━━━━━━━━━━━━━━━━━━━━ 4s 104ms/step - accuracy: 0.9346 - loss: 0.2914
Epoch 7/50
27/27 ━━━━━━━━━━━━━━━━━━━━ 3s 101ms/step - accuracy: 0.9480 - loss: 0.2676
Epoch 8/50
27/27 ━━━━━━━━━━━━━━━━━━━━ 7s 162ms/step - accuracy: 0.9471 - loss: 0.2566
Epoch 9/50
27/27 ━━━━━━━━━━━━━━━━━━━━ 4s 109ms/step - accuracy: 0.9493 - loss: 0.2555
Epoch 10/50
27/27 ━━━━━━━━━━━━━━━━━━━━ 5s 107ms/step - accuracy: 0.9438 - loss: 0.2545
Epoch 11/50
27/27 ━━━━━━━━━━━━━━━━━━━━ 6s 124ms/step - accuracy: 0.9500 - loss: 0.2370
Epoch 12/50
27/27 ━━━━━━━━━━━━━━━━━━━━ 5s 107ms/step

In [ ]:
text = "what is the fee"

token_text = tokenizer.texts_to_sequences([text])

In [ ]:
token_text

[[11, 7, 1, 42]]

In [ ]:
dic_word["what"]

11

In [ ]:
dic_word["fee"]

42

In [ ]:
token_text = tokenizer.texts_to_sequences([text])[0]

In [ ]:
token_text

[11, 7, 1, 42]

In [ ]:
padded_token_text = pad_sequences([token_text], maxlen=max_len, padding= 'pre')

In [ ]:
padded_token_text

array([[ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
         0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
         0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
         0,  0,  0,  0,  0, 11,  7,  1, 42]], dtype=int32)

In [ ]:
model.predict(padded_token_text)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 304ms/step


array([[7.93707358e-08, 7.97242683e-06, 2.25979346e-03, 1.05211337e-03,
        1.19804945e-02, 8.54999671e-05, 8.39331388e-01, 8.06803000e-05,
        3.69196044e-07, 4.71331186e-05, 6.02483124e-05, 1.52176081e-05,
        1.51051900e-05, 3.39257298e-07, 9.21434366e-06, 1.09608538e-01,
        8.05146992e-04, 4.34477202e-04, 4.74574190e-05, 7.77488822e-07,
        1.37751431e-05, 2.17836077e-05, 2.75394759e-05, 2.24364908e-06,
        8.95889173e-07, 7.36336290e-07, 4.99339603e-06, 2.88781666e-05,
        6.88972591e-07, 8.41634173e-05, 2.36653409e-06, 6.93194597e-05,
        4.36326861e-03, 5.55902204e-07, 3.65685059e-06, 1.68169354e-04,
        3.30473085e-05, 4.32641116e-07, 1.78993375e-07, 8.27470376e-06,
        2.66738175e-06, 1.76339399e-05, 2.33191508e-03, 1.82299664e-05,
        8.86754133e-03, 4.88990627e-04, 1.22220727e-05, 6.20626133e-06,
        4.23441371e-08, 7.63040407e-06, 7.57401358e-06, 4.13257067e-06,
        8.77125714e-08, 6.11216080e-07, 1.82014506e-03, 8.436153

In [ ]:
p = np.argmax(model.predict(padded_token_text))

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 52ms/step


In [ ]:
tokenizer.word_index.items()

dict_items([('the', 1), ('you', 2), ('i', 3), ('to', 4), ('a', 5), ('of', 6), ('is', 7), ('have', 8), ('will', 9), ('can', 10), ('what', 11), ('course', 12), ('program', 13), ('in', 14), ('for', 15), ('all', 16), ('sessions', 17), ('on', 18), ('be', 19), ('and', 20), ('this', 21), ('if', 22), ('am', 23), ('pay', 24), ('payment', 25), ('make', 26), ('we', 27), ('do', 28), ('subscription', 29), ('where', 30), ('rs', 31), ('so', 32), ('campusx', 33), ('session', 34), ('our', 35), ('paid', 36), ('join', 37), ('able', 38), ('your', 39), ('website', 40), ('placement', 41), ('fee', 42), ('data', 43), ('monthly', 44), ('month', 45), ('not', 46), ('get', 47), ('yes', 48), ('once', 49), ('past', 50), ('feb', 51), ('assistance', 52), ('science', 53), ('7', 54), ('5600', 55), ('are', 56), ('watch', 57), ('google', 58), ('by', 59), ('com', 60), ('mail', 61), ('from', 62), ('contact', 63), ('us', 64), ('at', 65), ('or', 66), ('doubt', 67), ('mentorship', 68), ('payments', 69), ('799', 70), ('total',

In [ ]:
for word, index in tokenizer.word_index.items():
    if index == p:
        text = text + " " + word
        print(text)

what is the fee of


In [ ]:
text

'what is the fee of'

In [ ]:
import time
sent = "what is the fee"
print(sent)
for i in range(10):
   token_sent = tokenizer.texts_to_sequences([sent])[0]
   padded_token_sent = pad_sequences([token_sent], maxlen= max_len, padding = "pre")
   pos = np.argmax(model.predict(padded_token_sent))

   for word, index in tokenizer.word_index.items():
        if index == pos :
           sent = sent+ " "+ word
           print(sent)
           time.sleep(3)


what is the fee
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 56ms/step
what is the fee of
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 83ms/step
what is the fee of monthly
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 48ms/step
what is the fee of monthly subscription
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 56ms/step
what is the fee of monthly subscription suppose
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 49ms/step
what is the fee of monthly subscription suppose if
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 51ms/step
what is the fee of monthly subscription suppose if i
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 50ms/step
what is the fee of monthly subscription suppose if i pay
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 48ms/step
what is the fee of monthly subscription suppose if i pay on
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 80ms/step
what is the fee of monthly subscription suppose if i pay on 15th
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 48ms/step
what is the fee of monthly subscription suppose if i pay on 15th jan
